# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [ ]:
s.split()

['Hi', 'there', 'Sam!']

 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [ ]:
print("The diameter of {} is {} kilometers".format(planet,diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
'hello' in d['k1'][3]['tricky'][3]['target']

True

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 

*   List item
*   List item


## 4.2 Create an array of 10 fives?

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
5*np.ones(10)

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [ ]:
even=np.array([])
np.append(even,list(range(20,35,2)))

array([20., 22., 24., 26., 28., 30., 32., 34.])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
np.array([[1,2,3],[4,5,6],[7,8,1]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [4]:
import pandas as pd


In [ ]:
x=np.array([[1,2],[4,5],[7,8]])

In [ ]:
pd.DataFrame(x)

0  1
0  1  2
1  4  5
2  7  8

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [6]:
dates=[]
for i in range(1,32):
  dates.append(str(i)+"-Jan-2023")
for i in range(1,11):
  dates.append(str(i)+"-Feb-2023")
pd.Series(dates)

0      1-Jan-2023
1      2-Jan-2023
2      3-Jan-2023
3      4-Jan-2023
4      5-Jan-2023
5      6-Jan-2023
6      7-Jan-2023
7      8-Jan-2023
8      9-Jan-2023
9     10-Jan-2023
10    11-Jan-2023
11    12-Jan-2023
12    13-Jan-2023
13    14-Jan-2023
14    15-Jan-2023
15    16-Jan-2023
16    17-Jan-2023
17    18-Jan-2023
18    19-Jan-2023
19    20-Jan-2023
20    21-Jan-2023
21    22-Jan-2023
22    23-Jan-2023
23    24-Jan-2023
24    25-Jan-2023
25    26-Jan-2023
26    27-Jan-2023
27    28-Jan-2023
28    29-Jan-2023
29    30-Jan-2023
30    31-Jan-2023
31     1-Feb-2023
32     2-Feb-2023
33     3-Feb-2023
34     4-Feb-2023
35     5-Feb-2023
36     6-Feb-2023
37     7-Feb-2023
38     8-Feb-2023
39     9-Feb-2023
40    10-Feb-2023
dtype: object

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
pd.DataFrame(lists)

0    1   2
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24